# Generated by Django 5.2.6 on 2025-09-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_jogos_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogos",
            name="amarelo_casa",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="amarelo_fora",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="chutes_casa",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="chutes_fora",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="defesa_casa",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="defesa_fora",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="escanteio_casa",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="escanteio_fora",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="faltas_casa",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="faltas_fora",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="gols_casa",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="gols_fora",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="vermelho_casa",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogos",
            name="vermelho_fora",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
