# Generated by Django 5.2.6 on 2025-09-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jogos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_casa", models.CharField(max_length=30)),
                ("time_fora", models.CharField(max_length=30)),
                ("dia", models.DateField()),
                ("gols_casa", models.IntegerField()),
                ("gols_fora", models.IntegerField()),
                ("ano", models.IntegerField()),
                ("rodada", models.IntegerField()),
                ("amarelo_casa", models.IntegerField()),
                ("amarelo_fora", models.IntegerField()),
                ("vermelho_casa", models.IntegerField()),
                ("vermelho_fora", models.IntegerField()),
                ("escanteio_casa", models.IntegerField()),
                ("escanteio_fora", models.IntegerField()),
                ("faltas_casa", models.IntegerField()),
                ("faltas_fora", models.IntegerField()),
                ("chutes_casa", models.IntegerField()),
                ("chutes_fora", models.IntegerField()),
                ("defesa_casa", models.IntegerField()),
                ("defesa_fora", models.IntegerField()),
            ],
        ),
    ]
